services:
  jaeger:
    image: jaegertracing/all-in-one:1.65.0
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    ports: ["127.0.0.1:16686:16686"]
  api:
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4318
  ledger:
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4318
  transfers:
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4318
  simulator:
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4318
  statements:
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4318
  notifications:
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4318
